general_config:
  algo_name: "PPO"
  env_name: "MiniGrid-Empty-5x5-v0"
  env_render: "rgb_array"
  project_name: "MiniGrid-Empty-5x5-PPO"
  device: cuda:1
  mode: train
  seed: 42
  train_steps: !!float 1e5
  eval_eps: 10
  eval_freq: 10000
  update_steps: 128
  gae_lambda: 0.95
  ppo_clip_param: 0.2
  ppo_epochs: 4
  mini_batch_size: 64
  actor_loss_coef: 1.0
  critic_loss_coef: 0.3
  entropy_coef: 0.01

sweep_config:
  method: bayes
  metric:
    goal: maximize
    name: val/reward
  parameters:
    actor_lr: 
      distribution: uniform
      max: 0.0003
      min: 0.0001
    critic_lr: 
      distribution: uniform
      max: 0.003
      min: 0.001
    gamma:
      max: 0.99
      min: 0.9

